#!/bin/bash
	# Write a script that asks the user to enter a number between 20 and 30. If the user
	# enters an invalid number or a non-number, ask again. Repeat until a satisfactory
	# number is entered.
	

	while true
	do
		printf "%s\n" "Enter a number from 20 to 30: "
		read x
		case $x in
			*[!0-9]*)
				printf "%s\n" "That’s not a number. You need to enter a number. Try again."
				continue
			;;
			*)
				if [ "$x" -le 30 ] && [ "$x" -ge 20 ]
				then
					printf "Good job!\n"
					break
				else
					printf "%s\n" "Your number has to be from 20 to 30. Try again."
					continue
				fi
			;;
		esac
	done
